packages:
  - apps/api
  - apps/admin-web

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/engines': true
  '@swc/core': set this to true or false
  esbuild: true
  prisma: true
  unrs-resolver: true
