import { defineCopy } from '@/lib/i18n'

// English from Figma 31:2307 (Salesmen) and 495:3932 (Add Salesman); Russian filter labels from 31:2307.
export const agentsCopy = defineCopy({
  en: {
    title: 'Salesmen',
    badge: 'Operations Live',
    description: 'Manage salesmen roster, territories, and live telemetry audit trails.',
    exportRoster: 'Export Roster',
    addSalesman: 'Add Salesman',
    search: 'Search salesmen...',
    dateFrom: 'Date from:',
    dateTo: 'Date to:',
    presets: { today: 'Today', yesterday: 'Yesterday', week: 'This week' },
    status: 'Status',
    region: 'Region',
    allStatus: 'All status',
    allRegions: 'All regions',
    statuses: { ACTIVE: 'Active', ON_LEAVE: 'On Leave', INACTIVE: 'Inactive' },
    applied: 'Applied:',
    remove: 'Remove filter',
    columns: { salesman: 'Salesman', code: 'Code', phone: 'Phone', locations: 'Locs', visits: 'Visits', photos: 'Photos', lastActivity: 'Last\nactivity', status: 'Status' },
    topPerformer: 'Top Performer',
    onLeave: 'On Leave',
    active: 'Active',
    inactive: 'Inactive',
    empty: 'No salesmen match these filters',
    actions: 'Actions',
    viewDetails: 'View Details',
    edit: 'Edit',
    pagination: { showing: 'Showing', of: 'of', show: 'Show:', perPage: 'per page', previous: 'Previous page', next: 'Next page', noun: 'salesmen' },
    form: {
      addTitle: 'Add sales representative',
      editTitle: 'Edit sales representative',
      subtitle: 'Manage your sales representatives, their routes and audit telemetry in real time.',
      close: 'Close',
      fullName: 'Full name', fullNamePlaceholder: 'e.g. Dovlet Orazov',
      code: 'Employee number / Code', generate: 'Generate code',
      phone: 'Contact phone', whatsapp: 'Additional phone / WhatsApp',
      notes: 'Notes / Route schedule', notesPlaceholder: 'Short description of the assigned sector or route days (e.g. Mon/Wed/Fri - sector A, Tue/Thu - sector B)...',
      visitPlan: 'Daily visit plan (shops)', visitSuffix: 'shops/day',
      auditPlan: 'Checklists / audits per day', auditSuffix: 'audits',
      region: 'Region / Sales territory', regionPlaceholder: 'Select a region',
      device: 'Work device binding (Tablet / Smartphone)', deviceNone: 'Not bound: binds on the first sign-in', deviceReset: 'Reset binding (new device)',
      status: 'Employee activity status', statuses: { ACTIVE: 'Active', ON_LEAVE: 'On leave', ARCHIVED: 'Archive' },
      cancel: 'Cancel', save: 'Save changes', resetPassword: 'Reset password',
      created: 'Salesman added', passwordNote: 'Temporary password (shown once, pass it to the salesman):', done: 'Done',
      errors: { required: 'Fill in the required fields', plan: 'The audit plan cannot exceed the visit plan', CONFLICT: 'This phone or code is already used, or the record was changed. Reload and try again.', generic: 'Could not save. Try again.' }
    }
  },
  ru: {
    title: 'Агенты',
    badge: 'В работе',
    description: 'Управляйте составом агентов, территориями и журналом активности.',
    exportRoster: 'Экспорт списка',
    addSalesman: 'Добавить агента',
    search: 'Поиск агентов...',
    dateFrom: 'Дата от:',
    dateTo: 'Дата до:',
    presets: { today: 'Сегодня', yesterday: 'Вчера', week: 'Текущая неделя' },
    status: 'Статус',
    region: 'Регион',
    allStatus: 'Все статусы',
    allRegions: 'Все регионы',
    statuses: { ACTIVE: 'Активен', ON_LEAVE: 'Отпуск', INACTIVE: 'Неактивен' },
    applied: 'Применено:',
    remove: 'Убрать фильтр',
    columns: { salesman: 'Агент', code: 'Код', phone: 'Телефон', locations: 'Точки', visits: 'Визиты', photos: 'Фото', lastActivity: 'Последняя\nактивность', status: 'Статус' },
    topPerformer: 'Лучший результат',
    onLeave: 'Отпуск',
    active: 'Активен',
    inactive: 'Неактивен',
    empty: 'Нет агентов по этим фильтрам',
    actions: 'Действия',
    viewDetails: 'Подробнее',
    edit: 'Редактировать',
    pagination: { showing: 'Показано', of: 'из', show: 'Показывать:', perPage: 'на странице', previous: 'Предыдущая страница', next: 'Следующая страница', noun: 'агентов' },
    form: {
      addTitle: 'Добавить торгового представителя',
      editTitle: 'Редактировать торгового представителя',
      subtitle: 'Управление штатом торговых представителей, маршрутами и телеметрией аудитов в реальном времени.',
      close: 'Закрыть',
      fullName: 'ФИО сотрудника', fullNamePlaceholder: 'Например, Довлет Оразов',
      code: 'Табельный номер / Код', generate: 'Сгенерировать код',
      phone: 'Контактный телефон', whatsapp: 'Дополнительный телефон / WhatsApp',
      notes: 'Примечания / График маршрута', notesPlaceholder: 'Краткое описание закрепленного сектора или маршрутных дней (напр. Пн/Ср/Пт - сектор А, Вт/Чт - сектор Б)...',
      visitPlan: 'Дневной план визитов (ТТ)', visitSuffix: 'точек/день',
      auditPlan: 'План чек-листов / аудитов в день', auditSuffix: 'аудитов',
      region: 'Регион / Территория продаж', regionPlaceholder: 'Выберите регион',
      device: 'Привязка рабочего устройства (Планшет / Смартфон)', deviceNone: 'Не привязано: привяжется при первом входе', deviceReset: 'Сбросить привязку (новое устройство)',
      status: 'Статус активности сотрудника', statuses: { ACTIVE: 'Активен', ON_LEAVE: 'Отпуск', ARCHIVED: 'Архив' },
      cancel: 'Отменить', save: 'Сохранить изменения', resetPassword: 'Сбросить пароль',
      created: 'Агент добавлен', passwordNote: 'Временный пароль (показывается один раз, передайте его агенту):', done: 'Готово',
      errors: { required: 'Заполните обязательные поля', plan: 'План аудитов не может превышать план визитов', CONFLICT: 'Этот телефон или код уже занят, либо запись изменена. Обновите страницу и повторите.', generic: 'Не удалось сохранить. Попробуйте ещё раз.' }
    }
  }
})

export type AgentsCopy = typeof agentsCopy.en
