import { defineCopy } from '@/lib/i18n'

// English from Figma 31:2307 (Salesmen) and 495:3932 (Add Salesman); Russian filter labels from 31:2307.
export const agentsCopy = defineCopy({
  en: {
    title: 'Salesmen',
    badge: 'Operations Live',
    description: 'Manage salesmen roster, territories, and live telemetry audit trails.',
    exportRoster: 'Export Roster',
    addSalesman: 'Add Salesman',
    kpis: {
      total: 'Total staff', people: ['person', 'people'], onStaff: '({n} on staff)',
      onRoute: 'On route', active: ['active', 'active'], ofPool: 'of the whole pool',
      audits: 'Audits completed', checklists: ['checklist', 'checklists'], vsPlan: 'vs daily plan',
      shops: 'Shops visited', outlets: 'outlets', remaining: '{n} left', stops: ['stop', 'stops'],
      photos: 'Photos uploaded', frames: ['photo', 'photos'], valid: 'valid',
      inactive: 'Inactive staff', needContact: 'Need contact (>{n} min)'
    },
    search: 'Search salesmen...',
    dateFrom: 'Date from:',
    dateTo: 'Date to:',
    presets: { today: 'Today', yesterday: 'Yesterday', week: 'This week' },
    status: 'Status',
    region: 'Region',
    allStatus: 'All status',
    allRegions: 'All regions',
    statuses: { ACTIVE: 'Active', ON_LEAVE: 'On Leave', INACTIVE: 'Inactive' },
    applied: 'Applied:',
    remove: 'Remove filter',
    columns: { salesman: 'Salesman', code: 'Code', phone: 'Phone', locations: 'Locs', visits: 'Visits', photos: 'Photos', lastActivity: 'Last\nactivity', status: 'Status' },
    topPerformer: 'Top Performer',
    onLeave: 'On Leave',
    active: 'Active',
    inactive: 'Inactive',
    empty: 'No salesmen match these filters',
    actions: 'Actions',
    viewDetails: 'View Details',
    edit: 'Edit',
    changePassword: 'Change password',
    pagination: { showing: 'Showing', of: 'of', show: 'Show:', perPage: 'per page', previous: 'Previous page', next: 'Next page', noun: 'salesmen' },
    details: {
      title: 'Activity history', live: 'Live audit', sector: 'Sector: {n}',
      online: 'Online (GPS active, accuracy {n} m)', offline: 'Offline (last signal: {n})', noSignal: 'Offline (no signal yet)',
      export: 'Export report (PDF/XLS)', exportPdf: 'PDF report', exportXls: 'Excel report',
      audits: 'All-time audits', checklists: ['checklist', 'checklists'],
      assigned: 'Assigned shops', outlets: ['outlet', 'outlets'],
      visited: 'Shops visited', ofShops: ['of {n} shop', 'of {n} shops'],
      photos: 'Total photos', frames: ['photo', 'photos'],
      route: 'Salesman route and tracking', recenter: 'Show the whole route', fullscreen: 'Full screen', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
      hereNow: 'here now', speed: '{n} km/h', battery: 'battery {n}%',
      timelineToday: 'Route history for today', timelineDay: 'Route history for {n}', checkpoints: ['checkpoint', 'checkpoints'], noStops: 'No route for this day',
      stop: { DONE: 'Done', MISSED: 'Missed', IN_PROGRESS: 'In progress', PLANNED: 'Planned' },
      syncing: 'Syncing…', plannedVisit: 'Planned visit', auditTask: 'Planned audit',
      photoReports: 'Audit photo reports', allPhotos: 'All {n} photos ↗', morePhotos: '+{n} more photos', openGallery: 'Open gallery', noPhotos: 'No photos for this period',
      history: 'Visit history', updatedAt: 'Updated at', total: 'Total: {n}', completed: 'Completed ({n})', missed: 'Missed ({n})',
      done: 'Completed', missedStatus: 'Missed', declined: 'Missed', duration: 'Duration: {n} min', code: 'Code', comment: 'Agent comment:', violation: 'Violation recorded:',
      thumbsMore: '+{n} photos', more: 'Show more', noVisits: 'No visits yet', today: 'Today', photoCount: '{n} photos'
    },
    form: {
      addTitle: 'Add sales representative',
      editTitle: 'Edit sales representative',
      subtitle: 'Manage your sales representatives, their routes and audit telemetry in real time.',
      close: 'Close',
      fullName: 'Full name', fullNamePlaceholder: 'e.g. Dovlet Orazov',
      code: 'Employee number / Code', generate: 'Generate code',
      phone: 'Contact phone', whatsapp: 'Additional phone / WhatsApp',
      notes: 'Notes / Route schedule', notesPlaceholder: 'Short description of the assigned sector or route days (e.g. Mon/Wed/Fri - sector A, Tue/Thu - sector B)...',
      visitPlan: 'Daily visit plan (shops)', visitSuffix: 'shops/day',
      auditPlan: 'Checklists / audits per day', auditSuffix: 'audits',
      region: 'Region / Sales territory', regionPlaceholder: 'Select a region',
      device: 'Work device binding (Tablet / Smartphone)', deviceNone: 'Not bound: binds on the first sign-in', deviceReset: 'Reset binding (new device)',
      status: 'Employee activity status', statuses: { ACTIVE: 'Active', ON_LEAVE: 'On leave', ARCHIVED: 'Archive' },
      cancel: 'Cancel', save: 'Save changes',
      password: 'Password', confirmPassword: 'Confirm password', passwordPlaceholder: '••••••••', showPassword: 'Show', hidePassword: 'Hide',
      rules: { length: 'At least 8 characters', letter: 'A letter', digit: 'A digit', match: 'Passwords match' },
      passwordTitle: 'Change password', newPassword: 'New password', passwordHint: 'The salesman is signed out on all devices and signs in with the new password.', savePassword: 'Save password',
      errors: { required: 'Fill in the required fields', field: 'Required', code: 'Latin letters, digits and dashes, 2–20 characters', visitPlan: 'From 1 to 100', confirm: 'The passwords do not match', phone: 'Enter a Turkmen mobile number: +993 6X XXXXXX (or 71, 72)', password: 'The password does not meet the rules below', plan: 'The audit plan cannot exceed the visit plan', CONFLICT: 'This phone or code is already used, or the record was changed. Reload and try again.', generic: 'Could not save. Try again.' }
    }
  },
  ru: {
    title: 'Агенты',
    badge: 'В работе',
    description: 'Управляйте составом агентов, территориями и журналом активности.',
    exportRoster: 'Экспорт списка',
    addSalesman: 'Добавить агента',
    kpis: {
      total: 'Всего сотрудников', people: ['чел.', 'чел.', 'чел.'], onStaff: '(в штате {n})',
      onRoute: 'На маршруте', active: ['активен', 'активны', 'активны'], ofPool: 'от общего пула',
      audits: 'Аудитов завершено', checklists: ['чек-лист', 'чек-листа', 'чек-листов'], vsPlan: 'к плану дня',
      shops: 'Магазинов посещено', outlets: 'ТТ', remaining: 'Осталось {n}', stops: ['точка', 'точки', 'точек'],
      photos: 'Фото загружено', frames: ['кадр', 'кадра', 'кадров'], valid: 'валидных',
      inactive: 'Неактивные сотр.', needContact: 'Требуют связи (>{n} мин)'
    },
    search: 'Поиск агентов...',
    dateFrom: 'Дата от:',
    dateTo: 'Дата до:',
    presets: { today: 'Сегодня', yesterday: 'Вчера', week: 'Текущая неделя' },
    status: 'Статус',
    region: 'Регион',
    allStatus: 'Все статусы',
    allRegions: 'Все регионы',
    statuses: { ACTIVE: 'Активен', ON_LEAVE: 'Отпуск', INACTIVE: 'Неактивен' },
    applied: 'Применено:',
    remove: 'Убрать фильтр',
    columns: { salesman: 'Агент', code: 'Код', phone: 'Телефон', locations: 'Точки', visits: 'Визиты', photos: 'Фото', lastActivity: 'Последняя\nактивность', status: 'Статус' },
    topPerformer: 'Лучший результат',
    onLeave: 'Отпуск',
    active: 'Активен',
    inactive: 'Неактивен',
    empty: 'Нет агентов по этим фильтрам',
    actions: 'Действия',
    viewDetails: 'Подробнее',
    edit: 'Редактировать',
    changePassword: 'Изменить пароль',
    pagination: { showing: 'Показано', of: 'из', show: 'Показывать:', perPage: 'на странице', previous: 'Предыдущая страница', next: 'Следующая страница', noun: 'агентов' },
    details: {
      title: 'История активности', live: 'Аудит в реальном времени', sector: 'Сектор: {n}',
      online: 'В сети (GPS активен, точность {n}м)', offline: 'Не в сети (последний сигнал: {n})', noSignal: 'Не в сети (сигнала ещё не было)',
      export: 'Экспорт отчёта (PDF/XLS)', exportPdf: 'Отчёт PDF', exportXls: 'Отчёт Excel',
      audits: 'Аудиты за все время', checklists: ['чек-лист', 'чек-листа', 'чек-листов'],
      assigned: 'Назначено магазинов', outlets: ['торговая точка', 'торговые точки', 'торговых точек'],
      visited: 'Посещено магазинов', ofShops: ['из {n} точки', 'из {n} точек', 'из {n} точек'],
      photos: 'Всего фотографий', frames: ['кадр', 'кадра', 'кадров'],
      route: 'Маршрут и трекинг сотрудника', recenter: 'Показать весь маршрут', fullscreen: 'Во весь экран', zoomIn: 'Приблизить', zoomOut: 'Отдалить',
      hereNow: 'сейчас здесь', speed: '{n} км/ч', battery: 'батарея {n}%',
      timelineToday: 'История маршрута за сегодня', timelineDay: 'История маршрута за {n}', checkpoints: ['чекпоинт', 'чекпоинта', 'чекпоинтов'], noStops: 'Маршрута на этот день нет',
      stop: { DONE: 'Выполнен', MISSED: 'Пропущен', IN_PROGRESS: 'В процессе', PLANNED: 'План' },
      syncing: 'Синхронизация…', plannedVisit: 'Плановый визит', auditTask: 'Плановый аудит',
      photoReports: 'Фотоотчёты аудитов', allPhotos: 'Все {n} кадров ↗', morePhotos: 'Еще +{n} фото', openGallery: 'Открыть галерею', noPhotos: 'Фото за этот период нет',
      history: 'История визитов', updatedAt: 'Обновлено в', total: 'В общем: {n}', completed: 'Завершён ({n})', missed: 'Пропущен ({n})',
      done: 'Завершён', missedStatus: 'Пропущен', declined: 'Отклонён', duration: 'Длительность: {n} мин', code: 'Код точки', comment: 'Комментарий агента:', violation: 'Зафиксировано нарушение:',
      thumbsMore: '+{n} фото', more: 'Показать ещё', noVisits: 'Визитов ещё нет', today: 'Сегодня', photoCount: '{n} фото'
    },
    form: {
      addTitle: 'Добавить торгового представителя',
      editTitle: 'Редактировать торгового представителя',
      subtitle: 'Управление штатом торговых представителей, маршрутами и телеметрией аудитов в реальном времени.',
      close: 'Закрыть',
      fullName: 'ФИО сотрудника', fullNamePlaceholder: 'Например, Довлет Оразов',
      code: 'Табельный номер / Код', generate: 'Сгенерировать код',
      phone: 'Контактный телефон', whatsapp: 'Дополнительный телефон / WhatsApp',
      notes: 'Примечания / График маршрута', notesPlaceholder: 'Краткое описание закрепленного сектора или маршрутных дней (напр. Пн/Ср/Пт - сектор А, Вт/Чт - сектор Б)...',
      visitPlan: 'Дневной план визитов (ТТ)', visitSuffix: 'точек/день',
      auditPlan: 'План чек-листов / аудитов в день', auditSuffix: 'аудитов',
      region: 'Регион / Территория продаж', regionPlaceholder: 'Выберите регион',
      device: 'Привязка рабочего устройства (Планшет / Смартфон)', deviceNone: 'Не привязано: привяжется при первом входе', deviceReset: 'Сбросить привязку (новое устройство)',
      status: 'Статус активности сотрудника', statuses: { ACTIVE: 'Активен', ON_LEAVE: 'Отпуск', ARCHIVED: 'Архив' },
      cancel: 'Отменить', save: 'Сохранить изменения',
      password: 'Пароль', confirmPassword: 'Подтвердите пароль', passwordPlaceholder: '••••••••', showPassword: 'Показать', hidePassword: 'Скрыть',
      rules: { length: 'Не менее 8 символов', letter: 'Буква', digit: 'Цифра', match: 'Пароли совпадают' },
      passwordTitle: 'Изменить пароль', newPassword: 'Новый пароль', passwordHint: 'Агент выйдет на всех устройствах и войдёт с новым паролем.', savePassword: 'Сохранить пароль',
      errors: { required: 'Заполните обязательные поля', field: 'Обязательное поле', code: 'Латинские буквы, цифры и дефис, 2–20 символов', visitPlan: 'От 1 до 100', confirm: 'Пароли не совпадают', phone: 'Введите мобильный номер Туркменистана: +993 6X XXXXXX (или 71, 72)', password: 'Пароль не соответствует требованиям ниже', plan: 'План аудитов не может превышать план визитов', CONFLICT: 'Этот телефон или код уже занят, либо запись изменена. Обновите страницу и повторите.', generic: 'Не удалось сохранить. Попробуйте ещё раз.' }
    }
  }
})

export type AgentsCopy = typeof agentsCopy.en
