import type { PrismaClient } from '../../generated/prisma/client.js'
import { newId } from '../../lib/ids.js'
import { localDate, startOfLocalDay } from '../../lib/time.js'
import type { SettingsService } from '../settings/settings.service.js'
import { orderStops, type Point } from './route-generator.js'

const toMinutes = (hhmm: string) => { const [h, m] = hhmm.split(':').map(Number); return h! * 60 + m! }
const dateOnly = (day: string) => new Date(`${day}T00:00:00Z`)

/** Daily routes (FR-009, research R-08). Routes are generated by jobs; there is no manual editing. */
export class RoutesService {
  private readonly prisma: PrismaClient
  private readonly settings: SettingsService
  constructor (prisma: PrismaClient, settings: SettingsService) {
    this.prisma = prisma
    this.settings = settings
  }

  /** Builds the agent's route for a company-local date; returns the existing one if already built. */
  async generate (agentId: string, day: string) {
    const existing = await this.prisma.route.findUnique({ where: { agentId_date: { agentId, date: dateOnly(day) } } })
    if (existing != null) return existing
    const agent = await this.prisma.agent.findUnique({ where: { userId: agentId }, include: { user: true, position: true, region: true } })
    if (agent == null || agent.user.status !== 'ACTIVE' || agent.workStatus !== 'ACTIVE') return null

    const s = await this.settings.get()
    const dayStart = startOfLocalDay(day, s.timezone)
    const dayEnd = new Date(dayStart.getTime() + 86_400_000)
    const due = await this.prisma.shop.findMany({
      where: { assignedAgentId: agentId, deletedAt: null, status: 'ACTIVE', OR: [{ nextDueAt: null }, { nextDueAt: { lt: dayEnd } }] },
      orderBy: [{ nextDueAt: { sort: 'asc', nulls: 'first' } }, { code: 'asc' }],
      take: agent.dailyVisitPlan
    })
    if (due.length === 0) return null

    const start: Point = agent.position ?? (agent.region.centroidLat != null ? { lat: agent.region.centroidLat, lng: agent.region.centroidLng! } : due[0]!)
    const ordered = orderStops(start, due)
    const from = toMinutes(s.workStart)
    const slot = Math.max(1, Math.floor((toMinutes(s.workEnd) - from) / ordered.length))
    const id = newId()
    try {
      await this.prisma.route.create({
        data: {
          id,
          agentId,
          date: dateOnly(day),
          stops: {
            create: ordered.map((shop, position) => ({
              id: newId(),
              shopId: shop.id,
              position,
              plannedAt: new Date(dayStart.getTime() + (from + position * slot) * 60_000),
              isAuditTask: position < agent.dailyAuditPlan
            }))
          }
        }
      })
    } catch {
      // A concurrent run created it first.
    }
    return this.prisma.route.findUnique({ where: { agentId_date: { agentId, date: dateOnly(day) } } })
  }

  /** Routes for every active agent for today (the daily job at workStart). */
  async generateAll (day?: string) {
    const s = await this.settings.get()
    const date = day ?? localDate(new Date(), s.timezone)
    const agents = await this.prisma.agent.findMany({ where: { workStatus: 'ACTIVE', user: { status: 'ACTIVE' } }, select: { userId: true } })
    for (const a of agents) await this.generate(a.userId, date)
    return { date, agents: agents.length }
  }

  /** At workEnd, stops that were not done become MISSED (gap A2: no reason is collected). */
  async endOfDay (day?: string) {
    const s = await this.settings.get()
    const date = day ?? localDate(new Date(), s.timezone)
    const { count } = await this.prisma.routeStop.updateMany({
      where: { route: { date: dateOnly(date) }, status: { in: ['PLANNED', 'IN_PROGRESS'] } },
      data: { status: 'MISSED' }
    })
    return { date, missed: count }
  }

  /** After a stop is DONE, re-order the remaining planned stops starting from that shop. */
  async reorderAfter (stopId: string) {
    const done = await this.prisma.routeStop.findUnique({ where: { id: stopId }, include: { shop: true } })
    if (done == null) return
    const rest = await this.prisma.routeStop.findMany({ where: { routeId: done.routeId, status: 'PLANNED' }, include: { shop: true } })
    if (rest.length === 0) return
    const ordered = orderStops(done.shop, rest.map((r) => ({ ...r, lat: r.shop.lat, lng: r.shop.lng })))
    const base = (await this.prisma.routeStop.aggregate({ where: { routeId: done.routeId }, _max: { position: true } }))._max.position ?? 0
    await this.prisma.$transaction(ordered.map((r, i) => this.prisma.routeStop.update({ where: { id: r.id }, data: { position: base + 1 + i } })))
  }

  /** The agent's route for today with its stops (synced to the device). */
  async today (agentId: string) {
    const s = await this.settings.get()
    const route = await this.prisma.route.findUnique({
      where: { agentId_date: { agentId, date: dateOnly(localDate(new Date(), s.timezone)) } },
      include: { stops: { orderBy: { position: 'asc' } } }
    })
    if (route == null) return { id: null, date: localDate(new Date(), s.timezone), stops: [] }
    return {
      id: route.id,
      date: route.date.toISOString().slice(0, 10),
      updatedAt: route.updatedAt.toISOString(),
      stops: route.stops.map((st) => ({
        id: st.id, shopId: st.shopId, position: st.position, plannedAt: st.plannedAt.toISOString(),
        isAuditTask: st.isAuditTask, status: st.status, auditId: st.auditId
      }))
    }
  }
}
